### PR TITLE
Adding Delete and Backup tool for Slack

### PR DESCRIPTION
**Pull request by uurtech**
Added a tool to delete and take backup of all of your messages/files in Slack

### CODE REVIEW

**Comment by ibnesayeed** [comment]
I also feel this is out of scope.

**Comment by anjackson** [comment]
Yeah, I think this is out of scope. Maybe we need to add some clearer guidelines though? I'd say we're trying to focus on preserving web sites rather than extracting data from web applications?

**Comment by ibnesayeed** [comment]
> Maybe we need to add some clearer guidelines though? I'd say we're trying to focus on preserving web sites rather than extracting data from web applications?

That should go in the `CONTRIBUTING.md` file. Also, we might want to note that dead/unmaintained entries should actively be moved to the `deprecated.md` file (we can also rename this file to something like `used-to-be-awesome.md` :wink:).

**Comment by ato** [comment]
If this was a tool primarily designed for archiving public slack channels I could see an argument for having it in the same category as Social Feed Manager. But since the archiving aspects seem incidental at best I think it's a stretch too far.

**Pull request closed without merging**
