### PR TITLE
Adding GLAM Workbench and Awesome Lists section

### PR DESCRIPTION
**Pull request by anjackson**
Adding the results of the GLAM Workbench work and re-jigging to 
make clearer links to other community resources. 

Also added a link to the Web Archiving Community list.

### CODE REVIEW

**Comment by anjackson** [comment]
Hm, webmemex.org has died....

**Comment by ibnesayeed** [comment]
I think, linking to the GitHub organization *WebMemex* would be a better choice as it will document the lineage.

**Comment by anjackson** [comment]
Sounds reasonable @ibnesayeed - I've updated accordingly.

**Comment by ibnesayeed** [comment]
Should we also add the following as sub-bullets in the ToC?

* Blogs and Scholarship
* Mailing Lists
* Slack
* Twitter

**Comment by anjackson** [comment]
I updated the TOC.

**Pull request merged**
